image: alpine/edge
packages:
  - python3
sources:
  - https://git.sr.ht/~thx/cabrillo
environment:
    project: cabrillo
tasks:
  - pytest: |
        cd ${project}
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        sudo pip3 install -r requirements_test.txt
        py.test --cov-report term-missing --cov cabrillo -v

